name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Installer les dépendances du projet
      - name: Install dependencies
        run: npm install

      # Vérifier le formatage
      - name: Check code format
        run: npm run format:check

      # Lancer les tests
      - name: Run tests
        run: npm test

      # Vérifier le linter
      - name: Run linter
        run: npm run lint

      # Installer MkDocs
      - name: Install MkDocs
        run: |
          python3 -m pip install --upgrade pip
          pip install mkdocs

      # Build la documentation
      - name: Build documentation
        run: mkdocs build

      # Construire le projet
      - name: Build project
        run: npm run build
